services:
  - type: web
    name: tender-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run interface/main.py
    envVars:
      - key: CLAUDE_API_KEY
        value: your-actual-key-here
